output_path: /p/user_pub/work/E3SM
project: E3SM
model_version: '1_1'
experiment: piControl
ensemble: ens1
non_native_grid: 180x360
atmospheric_resolution: 1deg
ocean_resolution: 60-30km

start_year: 1850
end_year: 2014

mapfiles: true
num_workers: 24
ini_path: /p/user_pub/e3sm/staging/ini_std/

data_paths:
    timeseries_atm: /p/user_pub/e3sm/baldwin32/bgc_processing/output/pp/ts/CASENAME/180x360/165yr/atm/
    timeseries_lnd: /p/user_pub/e3sm/baldwin32/bgc_processing/output/pp/ts/CASENAME/180x360/165yr/lnd/
    climo: /p/user_pub/e3sm/baldwin32/bgc_processing/output/pp/climos_regrid/180x360/CASENAME/165yr/