DEFAULT_WAREHOUSE_PATH: /p/user_pub/e3sm/warehouse/
DEFAULT_PUBLICATION_PATH: /p/user_pub/work/
DEFAULT_ARCHIVE_PATH: /p/user_pub/e3sm/archive/
DEFAULT_STATUS_PATH: /p/user_pub/e3sm/staging/status/
DEFAULT_PLOT_PATH: /var/www/acme/acme-diags/baldwin32/cmip_verification

grids:
  ne30_to_180x360: /home/zender1/data/maps/map_ne30np4_to_cmip6_180x360_aave.20181001.nc
  oEC60to30_to_180x360: /home/zender1/data/maps/map_oEC60to30v3_to_cmip6_180x360_aave.20181001.nc

cmip_metadata_path: /p/user_pub/e3sm/baldwin32/resources/CMIP6-Metadata/
cmip_tables_path: /home/baldwin32/projects/cmip6-cmor-tables/Tables/
vrt_map_path: /p/user_pub/e3sm/baldwin32/resources/vrt_remap_plev19.nc
cwl_workflows_path: /home/baldwin32/projects/e3sm_to_cmip/scripts/cwl_workflows/

cmip_atm_mon:
  frequency: 25
  num_workers: 12
  account: e3sm
  partition: debug
  timeout: "12:00:00"

cmip_atm_day:
  frequency: 10
  num_workers: 12
  account: e3sm
  partition: debug
  timeout: "12:00:00"
  sample_freq: day
  time_steps_per_day: "1"

cmip_atm_3hr:
  frequency: 10
  num_workers: 12
  account: e3sm
  partition: debug
  timeout: "12:00:00"
  sample_freq: 3hr
  time_steps_per_day: "8"

cmip_lnd_mon:
  frequency: 25
  num_workers: 12
  account: e3sm
  partition: debug
  timeout: "12:00:00"
  lnd_source_grid: /home/zender1/data/grids/ne30np4_pentagons.091226.nc
  lnd_destination_grid: /home/zender1/data/grids/cmip6_180x360_scrip.20181001.nc

cmip_ocn_mon:
  frequency: 1
  num_workers: 12
  account: e3sm
  partition: debug
  timeout: 1800
  slurm_timeout: "12:00:00"
  mpas_region_path: /p/user_pub/e3sm/baldwin32/resources/oEC60to30v3_Atlantic_region_and_southern_transect.nc
