package:
  name: esgfpub
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/E3SM-Project/esgfpub.git
  git_tag: {{ environ['TAG'] }}

build:
  noarch: python
  script: "python -m pip install . --no-deps -vv"
  string: {{ environ['BUILD_NAME'] }}

about:
    home: https://github.com/E3SM-Project/esgfpub
    summary: Automated publication to ESGF

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  
  run:
    - python >=3
    - tqdm
    - yaml
    - distributed
    - pexpect
    - xarray
    - netcdf4
    - vcs
    - myproxyclient
  
test:
  imports:
    - esgfpub
  commands:
    - esgfpub -h